apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: todo-route
spec:
  parentRefs:
    - name: todo-gateway
  rules:
    # /api -> todo-backend (ідеально: backend вже має /api/..)
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: todo-backend-svc
          port: 2233

    # все інше -> todo-app (HTML)
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: todo-app-svc
          port: 2222
