apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikipedia-todo-generator
spec:
  schedule: "*/1 * * * *"   # раз на годину
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: generator
              image: curlimages/curl:8.6.0
              command:
                - sh
                - -c
                - |
                  echo "Fetching random Wikipedia article..."

                  # Отримати Location header
                  URL=$(curl -sI https://en.wikipedia.org/wiki/Special:Random \
                        | grep -i '^location:' \
                        | awk '{print $2}' \
                        | tr -d '\r')

                  echo "Random article: $URL"

                  # Зібрати todo текст
                  TODO="Read $URL"

                  # POST у todo backend
                  curl -s -X POST \
                    http://todo-backend-svc:2233/api/todos \
                    -H "Content-Type: application/json" \
                    -d "\"$TODO\""

                  echo "Todo created: $TODO"
