apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - namespace.yaml
  - ../../base

  # локальна експозиція
  - ingress.yaml

  # локальний PV (для todo-app images)
  - todo-app-pv.yaml

patches:
  - path: patch-postgres-local-storageclass.yaml
  - path: patch-todoapp-pvc-local-storageclass.yaml
